name = "Liblet"
uuid = "5ecd16ac-4fd8-43d2-a9dd-e22a5cebe6f6"
authors = ["Manuele Lucchi <manuele.lucchi@studenti.unimi.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.4"